# Generated by Django 5.2.7 on 2026-01-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tech', 'Tech Fest'), ('cultural', 'Cultural Fest'), ('sports', 'Sports Meet')], max_length=20)),
            ],
        ),
    ]
